### ISSUE TITLE
概述里有一点用词重复

### ISSUE THREAD

**Issue by liul85** [dreamhead/patterns-of-distributed-systems#1]
- 在[模式](https://github.com/dreamhead/patterns-of-distributed-systems/blob/master/content/overview.md#%E6%A8%A1%E5%BC%8F)这里倒数第二句，`一种`有些重复
  > 一种使用模式的一种的方式是
  
  可以修改为 (原文里有interesting，我就带上了)
  > 使用模式的一种有意思的方式是
- [网络延迟](https://github.com/dreamhead/patterns-of-distributed-systems/blob/master/content/overview.md#%E7%BD%91%E7%BB%9C%E5%BB%B6%E8%BF%9F) 讲到脑裂问题，这里Quorum和法定人数，有时候用英文，有时候用中文，读起来有些晕
- [综合运用](https://github.com/dreamhead/patterns-of-distributed-systems/blob/master/content/overview.md#%E7%BB%BC%E5%90%88%E8%BF%90%E7%94%A8%E4%B8%80%E4%B8%AA%E5%88%86%E5%B8%83%E5%BC%8F%E7%B3%BB%E7%BB%9F%E7%A4%BA%E4%BE%8B)  这里第一段最后一句，句子读起来也有些重复，比如这里的`达成`，`存储`
  >简单来说，共识就是指，一组服务器达成就存储数据达成一致，以决定存储哪个数据要存储起来，什么时候数据对于客户端可见
 
  可以修改为
  >简单来说，共识就是指，一组服务器就存储数据达成一致，以决定哪个数据要存储起来，什么时候数据对于客户端可见

**Comment by dreamhead** [comment]
@liul85 多谢提出的问题，已经合并进去了。
